server:
  port: 8686

##  app.id：AppId是应用的身份信息，是配置中心获取配置的一个重要信息。
##  apollo.bootstrap.enabled：在应用启动阶段，向Spring容器注入被托管的application.properties文件的配置信息。
##  apollo.bootstrap.eagerLoad.enabled：将Apollo配置加载提到初始化日志系统之前。
##  logging.level.com.gf.controller：调整 controller 包的 log 级别，为了后面演示在配置中心动态配置日志级别。
app:
  id: springboot-apollo
apollo:
  meta: http://10.10.210.78:8761
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
